/* this is just a file that includes all headers that a user might include to look for errors */

#include <stdint.h>

/* apparently not defined anywhere should be in linux/socket.h> */

typedef unsigned short int sa_family_t;

struct sockaddr {
  sa_family_t sa_family;
  char sa_data[14];
};

/* we should not have to include these first as headers should include what they need */
#include <linux/types.h>
#include <linux/stddef.h>
#include <linux/unistd.h>
#include <linux/time.h>
#include <linux/net.h>
#include <linux/in.h>
#include <linux/in6.h>
#include <linux/if.h>

typedef __kernel_size_t size_t;

#include <linux/cdrom.h>
#include <linux/ncp_fs.h>
#include <linux/jffs2.h>
#include <linux/rds.h>
#include <linux/generic_serial.h>
#include <linux/fuse.h>
#include <linux/arcfb.h>
#include <linux/futex.h>
#include <linux/udf_fs_i.h>
#include <linux/acct.h>
#include <linux/ax25.h>
#include <linux/efs_fs_sb.h>
#include <linux/auto_fs.h>
#include <linux/scc.h>
#include <linux/in_route.h>
#include <linux/rtc.h>
#include <linux/atmlec.h>
#include <linux/tiocl.h>
#include <linux/netfilter_bridge/ebt_ip6.h>
#include <linux/netfilter_bridge/ebt_vlan.h>
#include <linux/netfilter_bridge/ebt_among.h>
#include <linux/netfilter_bridge/ebt_ulog.h>
#include <linux/netfilter_bridge/ebt_nflog.h>
#include <linux/netfilter_bridge/ebt_pkttype.h>
#include <linux/netfilter_bridge/ebt_arp.h>
#include <linux/netfilter_bridge/ebt_redirect.h>
#include <linux/netfilter_bridge/ebt_log.h>
#include <linux/netfilter_bridge/ebt_stp.h>
#include <linux/netfilter_bridge/ebt_ip.h>
#include <linux/netfilter_bridge/ebt_arpreply.h>
#include <linux/netfilter_bridge/ebt_limit.h>
#include <linux/netfilter_bridge/ebt_mark_t.h>
#include <linux/netfilter_bridge/ebtables.h>
#include <linux/netfilter_bridge/ebt_mark_m.h>
#include <linux/netfilter_bridge/ebt_nat.h>
#include <linux/netfilter_bridge/ebt_802_3.h>
#include <linux/uio.h>
#include <linux/magic.h>
#include <linux/screen_info.h>
#include <linux/fcntl.h>
#include <linux/b1lli.h>
#include <linux/if_link.h>
#include <linux/ixjuser.h>
#include <linux/elf-em.h>
#include <linux/ipmi.h>
#include <linux/ppp_defs.h>
#include <linux/if_phonet.h>
#include <linux/string.h>
#include <linux/irda.h>
#include <linux/sysctl.h>
#include <linux/x25.h>
#include <linux/netfilter_decnet.h>
#include <linux/ncp_no.h>
#include <linux/qnx4_fs.h>
#include <linux/virtio_pci.h>
#include <linux/in.h>
#include <linux/sock_diag.h>
#include <linux/tty.h>
#include <linux/i2o-dev.h>
#include <linux/atm_eni.h>
#include <linux/hdreg.h>
#include <linux/raid/md_p.h>
#include <linux/raid/md_u.h>
#include <linux/if_ppp.h>
#include <linux/if_bridge.h>
#include <linux/mempolicy.h>
#include <linux/selinux_netlink.h>
#include <linux/if_ec.h>
#include <linux/sonypi.h>
#include <linux/errno.h>
#include <linux/nubus.h>
#include <linux/vhost.h>
#include <linux/utime.h>
#include <linux/tipc.h>
#include <linux/types.h>
#include <linux/fib_rules.h>
#include <linux/irqnr.h>
#include <linux/agpgart.h>
#include <linux/edd.h>
#include <linux/param.h>
#include <linux/hdlc.h>
#include <linux/fsl_hypervisor.h>
#include <linux/usbdevice_fs.h>
#include <linux/dlmconstants.h>
#include <linux/posix_types.h>
#include <linux/gen_stats.h>
#include <linux/mmc/ioctl.h>
#include <linux/audit.h>
#include <linux/virtio_9p.h>
#include <linux/netfilter_arp.h>
#include <linux/isdn.h>
#include <linux/if_addr.h>
#include <linux/msg.h>
#include <linux/atmioc.h>
#include <linux/netlink.h>
#include <linux/fadvise.h>
#include <linux/nfs_mount.h>
#include <linux/if_packet.h>
#include <linux/fd.h>
#include <linux/securebits.h>
#include <linux/i8k.h>
#include <linux/meye.h>
#include <linux/ip_vs.h>
#include <linux/poll.h>
#include <linux/bsg.h>
#include <linux/pg.h>
#include <linux/ptrace.h>
#include <linux/nfs3.h>
#include <linux/serial_core.h>
#include <linux/map_to_7segment.h>
#include <linux/dlm_netlink.h>
#include <linux/ipmi_msgdefs.h>
#include <linux/msdos_fs.h>
#include <linux/netfilter_ipv6/ip6t_REJECT.h>
#include <linux/netfilter_ipv6/ip6t_LOG.h>
#include <linux/netfilter_ipv6/ip6t_HL.h>
#include <linux/netfilter_ipv6/ip6t_opts.h>
#include <linux/netfilter_ipv6/ip6t_frag.h>
#include <linux/netfilter_ipv6/ip6t_ipv6header.h>
#include <linux/netfilter_ipv6/ip6t_hl.h>
#include <linux/netfilter_ipv6/ip6t_ah.h>
#include <linux/netfilter_ipv6/ip6t_rt.h>
#include <linux/netfilter_ipv6/ip6t_mh.h>
#include <linux/netfilter_ipv6/ip6_tables.h>
#include <linux/netfilter_ipv4/ipt_ULOG.h>
#include <linux/netfilter_ipv4/ipt_realm.h>
#include <linux/netfilter_ipv4/ipt_ECN.h>
#include <linux/netfilter_ipv4/ipt_LOG.h>
#include <linux/netfilter_ipv4/ipt_addrtype.h>
#include <linux/netfilter_ipv4/ipt_SAME.h>
#include <linux/netfilter_ipv4/ipt_ah.h>
#include <linux/netfilter_ipv4/ipt_ecn.h>
#include <linux/netfilter_ipv4/ip_tables.h>
#include <linux/netfilter_ipv4/ipt_ttl.h>
#include <linux/netfilter_ipv4/ip_queue.h>
#include <linux/netfilter_ipv4/ipt_TTL.h>
#include <linux/netfilter_ipv4/ipt_REJECT.h>
#include <linux/netfilter_ipv4/ipt_CLUSTERIP.h>
#include <linux/parport.h>
#include <linux/wanrouter.h>
#include <linux/tc_ematch/tc_em_text.h>
#include <linux/tc_ematch/tc_em_meta.h>
#include <linux/tc_ematch/tc_em_cmp.h>
#include <linux/tc_ematch/tc_em_nbyte.h>
#include <linux/if_bonding.h>
#include <linux/perf_event.h>
#include <linux/spi/spidev.h>
#include <linux/fanotify.h>
#include <linux/cm4000_cs.h>
#include <linux/netfilter/xt_esp.h>
#include <linux/netfilter/xt_MARK.h>
#include <linux/netfilter/xt_iprange.h>
#include <linux/netfilter/nf_conntrack_tuple_common.h>
#include <linux/netfilter/xt_DSCP.h>
#include <linux/netfilter/nfnetlink.h>
#include <linux/netfilter/xt_policy.h>
#include <linux/netfilter/xt_realm.h>
#include <linux/netfilter/xt_RATEEST.h>
#include <linux/netfilter/xt_cpu.h>
#include <linux/netfilter/xt_CONNMARK.h>
#include <linux/netfilter/xt_ipvs.h>
#include <linux/netfilter/nfnetlink_conntrack.h>
#include <linux/netfilter/xt_u32.h>
#include <linux/netfilter/nfnetlink_queue.h>
#include <linux/netfilter/xt_time.h>
#include <linux/netfilter/nf_conntrack_common.h>
#include <linux/netfilter/xt_CT.h>
#include <linux/netfilter/xt_conntrack.h>
#include <linux/netfilter/x_tables.h>
#include <linux/netfilter/xt_pkttype.h>
#include <linux/netfilter/xt_tcpudp.h>
#include <linux/netfilter/xt_multiport.h>
#include <linux/netfilter/xt_limit.h>
#include <linux/netfilter/xt_SECMARK.h>
#include <linux/netfilter/xt_string.h>
#include <linux/netfilter/xt_state.h>
#include <linux/netfilter/xt_IDLETIMER.h>
#include <linux/netfilter/xt_sctp.h>
#include <linux/netfilter/xt_recent.h>
#include <linux/netfilter/xt_CONNSECMARK.h>
#include <linux/netfilter/xt_physdev.h>
#include <linux/netfilter/nf_nat.h>
#include <linux/netfilter/xt_nfacct.h>
#include <linux/netfilter/xt_addrtype.h>
#include <linux/netfilter/nfnetlink_acct.h>
#include <linux/netfilter/xt_LED.h>
#include <linux/netfilter/xt_TEE.h>
#include <linux/netfilter/xt_connbytes.h>
#include <linux/netfilter/nf_conntrack_sctp.h>
#include <linux/netfilter/xt_connlimit.h>
#include <linux/netfilter/xt_length.h>
#include <linux/netfilter/xt_mac.h>
#include <linux/netfilter/xt_dccp.h>
#include <linux/netfilter/xt_TCPOPTSTRIP.h>
#include <linux/netfilter/xt_osf.h>
#include <linux/netfilter/xt_owner.h>
#include <linux/netfilter/xt_cluster.h>
#include <linux/netfilter/nfnetlink_compat.h>
#include <linux/netfilter/nf_conntrack_tcp.h>
#include <linux/netfilter/xt_TPROXY.h>
#include <linux/netfilter/xt_devgroup.h>
#include <linux/netfilter/xt_connmark.h>
#include <linux/netfilter/xt_CHECKSUM.h>
#include <linux/netfilter/xt_mark.h>
#include <linux/netfilter/xt_hashlimit.h>
#include <linux/netfilter/nf_conntrack_ftp.h>
#include <linux/netfilter/xt_helper.h>
#include <linux/netfilter/ipset/ip_set_bitmap.h>
#include <linux/netfilter/ipset/ip_set_list.h>
#include <linux/netfilter/ipset/ip_set_hash.h>
#include <linux/netfilter/ipset/ip_set.h>
#include <linux/netfilter/xt_quota.h>
#include <linux/netfilter/xt_socket.h>
#include <linux/netfilter/xt_dscp.h>
#include <linux/netfilter/xt_ecn.h>
#include <linux/netfilter/xt_rateest.h>
#include <linux/netfilter/xt_CLASSIFY.h>
#include <linux/netfilter/nfnetlink_log.h>
#include <linux/netfilter/xt_AUDIT.h>
#include <linux/netfilter/xt_TCPMSS.h>
#include <linux/netfilter/xt_statistic.h>
#include <linux/netfilter/xt_tcpmss.h>
#include <linux/netfilter/xt_NFQUEUE.h>
#include <linux/netfilter/xt_NFLOG.h>
#include <linux/netfilter/xt_set.h>
#include <linux/netfilter/xt_comment.h>
#include <linux/usb/gadgetfs.h>
#include <linux/usb/functionfs.h>
#include <linux/usb/ch11.h>
#include <linux/usb/g_printer.h>
#include <linux/usb/midi.h>
#include <linux/usb/audio.h>
#include <linux/usb/tmc.h>
#include <linux/usb/video.h>
#include <linux/usb/ch9.h>
#include <linux/usb/cdc.h>
#include <linux/genetlink.h>
#include <linux/rose.h>
#include <linux/if_vlan.h>
#include <linux/cycx_cfm.h>
#include <linux/if_frad.h>
#include <linux/reiserfs_fs.h>
#include <linux/ethtool.h>
#include <linux/serial_reg.h>
#include <linux/joystick.h>
#include <linux/blkpg.h>
#include <linux/firewire-cdev.h>
#include <linux/if_hippi.h>
#include <linux/wireless.h>
#include <linux/wimax/i2400m.h>
#include <linux/bfs_fs.h>
#include <linux/affs_hardblocks.h>
#include <linux/atmppp.h>
#include <linux/xfrm.h>
#include <linux/omap3isp.h>
#include <linux/watchdog.h>
#include <linux/inet_diag.h>
#include <linux/nfs4.h>
#include <linux/l2tp.h>
#include <linux/cciss_ioctl.h>
#include <linux/ptp_clock.h>
#include <linux/if_x25.h>
#include <linux/raw.h>
#include <linux/fs.h>
#include <linux/gfs2_ondisk.h>
#include <linux/if_ltalk.h>
#include <linux/atalk.h>
#include <linux/dm-ioctl.h>
#include <linux/sonet.h>
#include <linux/capability.h>
#include <linux/signalfd.h>
#include <linux/atmapi.h>
#include <linux/nvram.h>
#include <linux/utsname.h>
#include <linux/coda_psdev.h>
#include <linux/phantom.h>
#include <linux/falloc.h>
#include <linux/can.h>
#include <linux/romfs_fs.h>
#include <linux/netdevice.h>
#include <linux/resource.h>
#include <linux/sound.h>
#include <linux/swab.h>
#include <linux/tcp.h>
#include <linux/unistd.h>
#include <linux/filter.h>
#include <linux/if_ether.h>
#include <linux/if_slip.h>
#include <linux/oom.h>
#include <linux/v4l2-mediabus.h>
#include <linux/ioctl.h>
#include <linux/major.h>
#include <linux/virtio_console.h>
#include <linux/input.h>
#include <linux/atmmpc.h>
#include <linux/virtio_blk.h>
#include <linux/ppdev.h>
#include <linux/atm_nicstar.h>
#include <linux/if_eql.h>
#include <linux/ultrasound.h>
#include <linux/ivtvfb.h>
#include <linux/times.h>
#include <linux/nfs2.h>
#include <linux/atmsvc.h>
#include <linux/capi.h>
#include <linux/udp.h>
#include <linux/sem.h>
#include <linux/ncp_mount.h>
#include <linux/version.h>
#include <linux/connector.h>
#include <linux/veth.h>
#include <linux/netfilter_ipv6.h>
#include <linux/auxvec.h>
#include <linux/if.h>
#include <linux/fb.h>
#include <linux/netrom.h>
#include <linux/atmbr2684.h>
#include <linux/eventpoll.h>
#include <linux/neighbour.h>
#include <linux/errqueue.h>
#include <linux/fiemap.h>
#include <linux/ip6_tunnel.h>
#include <linux/sockios.h>
#include <linux/omapfb.h>
#include <linux/random.h>
#include <linux/virtio_config.h>
#include <linux/icmp.h>
#include <linux/hdlcdrv.h>
#include <linux/keyboard.h>
#include <linux/ipsec.h>
#include <linux/auto_fs4.h>
#include <linux/loop.h>
#include <linux/nfs.h>
#include <linux/som.h>
#include <linux/if_team.h>
#include <linux/firewire-constants.h>
#include <linux/phonet.h>
#include <linux/pfkeyv2.h>
#include <linux/ipc.h>
#include <linux/nfs_fs.h>
#include <linux/nfs_idmap.h>
#include <linux/stddef.h>
#include <linux/kvm_para.h>
#include <linux/synclink.h>
#include <linux/if_addrlabel.h>
#include <linux/mman.h>
#include <linux/blktrace_api.h>
#include <linux/pkt_cls.h>
#include <linux/hid.h>
#include <linux/if_pppox.h>
#include <linux/igmp.h>
#include <linux/bpqether.h>
#include <linux/sdla.h>
#include <linux/adb.h>
#include <linux/adfs_fs.h>
#include <linux/dlm_device.h>
#include <linux/binfmts.h>
#include <linux/atm_he.h>
#include <linux/route.h>
#include <linux/if_tunnel.h>
#include <linux/prctl.h>
#include <linux/dm-log-userspace.h>
#include <linux/uvcvideo.h>
#include <linux/pkt_sched.h>
#include <linux/const.h>
#include <linux/netfilter.h>
#include <linux/dvb/ca.h>
#include <linux/dvb/dmx.h>
#include <linux/dvb/audio.h>
#include <linux/dvb/version.h>
#include <linux/dvb/video.h>
#include <linux/dvb/net.h>
#include <linux/dvb/osd.h>
#include <linux/dvb/frontend.h>
#include <linux/coda.h>
#include <linux/coff.h>
#include <linux/apm_bios.h>
#include <linux/elf.h>
#include <linux/dccp.h>
#include <linux/atmarp.h>
#include <linux/unix_diag.h>
#include <linux/hpet.h>
#include <linux/net.h>
#include <linux/minix_fs.h>
#include <linux/if_fddi.h>
#include <linux/cciss_defs.h>
#include <linux/if_tun.h>
#include <linux/isdn_ppp.h>
#include <linux/cuda.h>
#include <linux/atmclip.h>
#include <linux/nfsd/debug.h>
#include <linux/nfsd/nfsfh.h>
#include <linux/nfsd/stats.h>
#include <linux/nfsd/export.h>
#include <linux/nfs4_mount.h>
#include <linux/mtio.h>
#include <linux/ext2_fs.h>
#include <linux/netfilter_ipv4.h>
#include <linux/isdn/capicmd.h>
#include <linux/hiddev.h>
#include <linux/if_arcnet.h>
#include <linux/gigaset_dev.h>
#include <linux/kernelcapi.h>
#include <linux/personality.h>
#include <linux/kernel.h>
#include <linux/sunrpc/debug.h>
#include <linux/timex.h>
#include <linux/mqueue.h>
#include <linux/mii.h>
#include <linux/lp.h>
#include <linux/if_strip.h>
#include <linux/serio.h>
#include <linux/wimax.h>
#include <linux/netfilter_bridge.h>
#include <linux/cgroupstats.h>
#include <linux/inotify.h>
#include <linux/atmdev.h>
#include <linux/pmu.h>
#include <linux/mroute.h>
#include <linux/if_cablemodem.h>
#include <linux/snmp.h>
#include <linux/suspend_ioctls.h>
#include <linux/kvm.h>
#include <linux/tipc_config.h>
#include <linux/if_plip.h>
#include <linux/dlm.h>
#include <linux/fdreg.h>
#include <linux/ivtv.h>
#include <linux/un.h>
#include <linux/virtio_balloon.h>
#include <linux/radeonfb.h>
#include <linux/atmsap.h>
#include <linux/pci.h>
#include <linux/videodev2.h>
#include <linux/a.out.h>
#include <linux/elfcore.h>
#include <linux/atm_tcp.h>
#include <linux/baycom.h>
#include <linux/ipv6_route.h>
#include <linux/virtio_ids.h>
#include <linux/elf-fdpic.h>
#include <linux/kd.h>
#include <linux/dcbnl.h>
#include <linux/reiserfs_xattr.h>
#include <linux/virtio_rng.h>
#include <linux/netfilter_arp/arp_tables.h>
#include <linux/netfilter_arp/arpt_mangle.h>
#include <linux/ncp.h>
#include <linux/atm_idt77105.h>
#include <linux/if_pppol2tp.h>
#include <linux/nl80211.h>
#include <linux/quota.h>
#include <linux/if_fc.h>
#include <linux/i2c-dev.h>
#include <linux/if_arp.h>
#include <linux/cn_proc.h>
#include <linux/isdn_divertif.h>
#include <linux/isdnif.h>
#include <linux/if_alg.h>
#include <linux/media.h>
#include <linux/socket.h>
#include <linux/ip.h>
#include <linux/reboot.h>
#include <linux/can/netlink.h>
#include <linux/can/raw.h>
#include <linux/can/error.h>
#include <linux/can/gw.h>
#include <linux/can/bcm.h>
#include <linux/mroute6.h>
#include <linux/aio_abi.h>
#include <linux/time.h>
#include <linux/net_dropmon.h>
#include <linux/n_r3964.h>
#include <linux/soundcard.h>
#include <linux/dqblk_xfs.h>
#include <linux/sched.h>
#include <linux/patchkey.h>
#include <linux/llc.h>
#include <linux/toshiba.h>
#include <linux/limits.h>
#include <linux/flat.h>
#include <linux/taskstats.h>
#include <linux/termios.h>
#include <linux/chio.h>
#include <linux/gameport.h>
#include <linux/dlm_plock.h>
#include <linux/if_tr.h>
#include <linux/kdev_t.h>
#include <linux/wait.h>
#include <linux/stat.h>
#include <linux/hysdn_if.h>
#include <linux/telephony.h>
#include <linux/net_tstamp.h>
#include <linux/cdk.h>
#include <linux/signal.h>
#include <linux/cramfs_fs.h>
#include <linux/ppp-comp.h>
#include <linux/hidraw.h>
#include <linux/nfsacl.h>
#include <linux/in6.h>
#include <linux/pktcdvd.h>
#include <linux/icmpv6.h>
#include <linux/rtnetlink.h>
#include <linux/comstats.h>
#include <linux/mmtimer.h>
#include <linux/rfkill.h>
#include <linux/caif/caif_socket.h>
#include <linux/caif/if_caif.h>
#include <linux/tc_act/tc_pedit.h>
#include <linux/tc_act/tc_csum.h>
#include <linux/tc_act/tc_ipt.h>
#include <linux/tc_act/tc_gact.h>
#include <linux/tc_act/tc_skbedit.h>
#include <linux/tc_act/tc_mirred.h>
#include <linux/tc_act/tc_nat.h>
#include <linux/uinput.h>
#include <linux/atm.h>
#include <linux/i2c.h>
#include <linux/keyctl.h>
#include <linux/vt.h>
#include <linux/iso_fs.h>
#include <linux/virtio_net.h>
#include <linux/shm.h>
#include <linux/blk_types.h>
#include <linux/nbd.h>
#include <linux/ipx.h>
#include <linux/ipv6.h>
#include <linux/xattr.h>
#include <linux/atm_zatm.h>
#include <linux/dn.h>
#include <linux/hdlc/ioctl.h>
#include <linux/cyclades.h>
#include <linux/pci_regs.h>
#include <linux/qnxtypes.h>
#include <linux/matroxfb.h>
#include <linux/serial.h>
#include <linux/virtio_ring.h>
#include <linux/if_infiniband.h>
#include <linux/v4l2-subdev.h>
#include <linux/pps.h>
#include <scsi/scsi_netlink.h>
#include <scsi/scsi_bsg_fc.h>
#include <scsi/fc/fc_ns.h>
#include <scsi/fc/fc_gs.h>
#include <scsi/fc/fc_fs.h>
#include <scsi/fc/fc_els.h>
#include <scsi/scsi_netlink_fc.h>
#include <mtd/mtd-user.h>
#include <mtd/inftl-user.h>
#include <mtd/nftl-user.h>
#include <mtd/mtd-abi.h>
#include <mtd/ubi-user.h>
#include <asm-generic/statfs.h>
#include <asm-generic/fcntl.h>
#include <asm-generic/int-l64.h>
#include <asm-generic/errno.h>
#include <asm-generic/int-ll64.h>
#include <asm-generic/types.h>
#include <asm-generic/param.h>
#include <asm-generic/posix_types.h>
#include <asm-generic/poll.h>
#include <asm-generic/ioctls.h>
#include <asm-generic/shmbuf.h>
#include <asm-generic/mman-common.h>
#include <asm-generic/errno-base.h>
#include <asm-generic/shmparam.h>
#include <asm-generic/resource.h>
#include <asm-generic/swab.h>
#include <asm-generic/unistd.h>
#include <asm-generic/ioctl.h>
#include <asm-generic/auxvec.h>
#include <asm-generic/sockios.h>
#include <asm-generic/signal-defs.h>
#include <asm-generic/mman.h>
#include <asm-generic/setup.h>
#include <asm-generic/bitsperlong.h>
#include <asm-generic/ipcbuf.h>
#include <asm-generic/termbits.h>
#include <asm-generic/socket.h>
#include <asm-generic/ucontext.h>
#include <asm-generic/termios.h>
#include <asm-generic/sembuf.h>
#include <asm-generic/stat.h>
#include <asm-generic/signal.h>
#include <asm-generic/msgbuf.h>
#include <asm-generic/siginfo.h>
#include <sound/compress_offload.h>
#include <sound/asequencer.h>
#include <sound/emu10k1.h>
#include <sound/asound.h>
#include <sound/sfnt_info.h>
#include <sound/asound_fm.h>
#include <sound/hdspm.h>
#include <sound/hdsp.h>
#include <sound/compress_params.h>
#include <sound/sb16_csp.h>
#include <rdma/ib_user_sa.h>
#include <rdma/rdma_user_cm.h>
#include <rdma/ib_user_verbs.h>
#include <rdma/rdma_netlink.h>
#include <rdma/ib_user_cm.h>
#include <rdma/ib_user_mad.h>
#include <drm/exynos_drm.h>
#include <drm/r128_drm.h>
#include <drm/via_drm.h>
#include <drm/savage_drm.h>
#include <drm/i915_drm.h>
#include <drm/drm_mode.h>
#include <drm/mga_drm.h>
#include <drm/drm_fourcc.h>
#include <drm/drm.h>
#include <drm/i810_drm.h>
#include <drm/radeon_drm.h>
#include <drm/vmwgfx_drm.h>
#include <drm/sis_drm.h>
#include <drm/nouveau_drm.h>
#include <drm/drm_sarea.h>
#include <xen/privcmd.h>
#include <xen/evtchn.h>
#include <video/uvesafb.h>
#include <video/edid.h>
#include <video/sisfb.h>

int main() {
  return 0;
}

